[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mote"
version = "0.1.0"
authors = [
    { name = "Hugo H" },
    { name = "Mark A" },
]
description = "A tiny terminal text editor"
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
mote = "mote.main:main"